### ISSUE TITLE
Please include dark theme.

### ISSUE THREAD

**Issue by Digikid1** [thisdotvoid/youtube-classic-extension#4]
While I absolutely LOVE your extension I find the white WAY too bright and actually much prefer the dark theme option that was on regular Youtube.  Is there any way that you can bring that to this addon please?

**Comment by thisdotvoid** [comment]
That's definitely doable, but I don't think I have time for that now. However, [Enhancer for YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/) can already do that, both extensions can work together.

**Comment by Digikid1** [comment]
Thank you!  That addon is simply fantastic!!!  I used the Ubuntu theme as
it is perfect for me.

Thanks again and keep up the excellent work!
