### ISSUE TITLE
Scoping the change

### ISSUE THREAD

**Issue by AZanellato** [thisdotvoid/youtube-classic-extension#5]
I saw that the code gets the youtube url with a wildcard at the end and my experience is actually a lot better on the home page of youtube, but I do prefer the new video page (although I do know that that is a really bad offender on load times, I don't care too much.) 

Would it be possible to have something of the effect of 
```javascript
var url = "www.youtube.com/*" 
if( url.indexOf("watch") > 0)
  url = null;
```

Or would that break everything?

**Comment by thisdotvoid** [comment]
nope, that won't work. you have to explicitly unset cookie on pages you want to whitelist. additionally, you have to force page reload when you click a video from home page, or it will only work if you directly go to video page.

**Comment by thisdotvoid** [comment]
see [scoping branch](/thisdotvoid/youtube-classic-extension/tree/scoping)
