### ISSUE TITLE
Bug report - video still centered, but black bar to left side.

### ISSUE THREAD

**Issue by McDouggal** [thisdotvoid/youtube-classic-extension#6]
Image https://i.imgur.com/dSyI4PO.png

Uninstalling and reinstalling the extension does not work.

I have the latest version of Waterfox, but cannot really test on firefox.

**Comment by MTaylor077** [comment]
I can confirm that this is also happening on the latest version of Firefox. I don't think its an issue with the extension though, I think Google changed something on their end to do with the classic YouTube layout, when the cookie PREF has been set.

**Comment by CybrCat** [comment]
Have the same issue, just started for me within the last few hours. Also noticed that the amount of spill over from the player window depends on the browser window width.

**Comment by gyrocam** [comment]
Can confirm. Same issue using Firefox 61.0.2 (64-bit) Quantum. Video pushed to the right, overlaps thumbnails and leaves black void at left.

**Comment by thisdotvoid** [comment]
Can't reproduce on 61.0.1/linux. Maybe it happens on bigger screens than 13-inch laptop?

**Comment by Jakob900** [comment]
This was happening to me a few hours ago but just checked again and it looks normal now

**Comment by McDouggal** [comment]
This has been fixed for me as well.
