### ISSUE TITLE
Cookie manipulation seems unsecure?

### ISSUE THREAD

**Issue by rynokins** [thisdotvoid/youtube-classic-extension#7]
I was getting some strange search results on the initial page of google, which went away with the add-on disabled. I wanted to see if the add-on was somehow compromised so I cleared cookies and then added it back to Firefox and the spam results were gone. I have some suspicions that the JS you're using to manipulate the cookies might have been getting hijacked…?

**Comment by thisdotvoid** [comment]
I have no idea what does the number 42088 (which is injected in cookies) mean to google internally, it was set to my own account when the opt-out button was still in the menu. Recently I found out that only number 8 is enough, but didn't update extension, as I have no idea how does these numbers work. that all this extension does.
